baseURL = "/"
languageCode = "pt-pt"
title = "Takuji Takai"
theme="archie"
copyright = "© Takuji"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "ezhil-demo"

[params]
	mode="dark"
	useCDN=false
	subtitle = ". . ."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ttakuji"

[[menu.main]]
name = "Tutoriais"
url = "/post"
weight = 1

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
